import { Review } from './types'

export const reviews: Review[] = [
	{
		id: 0,
		author: 'Emmet',
		avatar: 'https://github.com/shadcn.png',
		title: 'Everything is awesome!',
		content: `Everything is awesome. Everything is cool when you're part of a team. Everything is awesome. When you're living out a dream.`,
		stars: 5,
	},
	{
		id: 1,
		author: 'Pengfei Z.',
		avatar: 'https://github.com/gaearon.png',
		title: 'Excellent choice!',
		content: `They quickly assigned a mentor (Mina) to me. She's very supportive, patient and very productive, and all my assessments were marked within 2 days. I would like to say “Thank you Mina and The MIIA team!”.`,
		stars: 5,
	},
	{
		id: 2,
		author: 'Farrah G.',
		avatar: 'https://github.com/sugoi-wada.png',
		title: 'Matched Qualities!',
		content: `I'm in my first year of using MIIA and I have been guided by the support team every step of the way to get the perfect mentor that matches with my qualities and aligned with my values.`,
		stars: 5,
	},
	{
		id: 3,
		author: 'Lucy L.',
		avatar: 'https://github.com/sugoi-wada.png',
		title: 'Highly Recommended!',
		content: `This mentor program is amazing! They provided the best student support ever. They spent generous amount of time explaining the answers to your questions. I appreciate the way I was assisted with my assignments. 100% happy with the results!`,
		stars: 5,
	},
	{
		id: 4,
		author: 'Bianca T.',
		avatar: 'https://github.com/amandavilela.png',
		title: '💯',
		content: `Everything turned out really great! I've always felt supported from the beginning and always able to reach out for help when needed. Special shout-out to Miller (my mentor) for his amazing support through both my cert 4 and diploma in finance.`,
		stars: 5,
	},
]

export const reviewData: Review[] = [
	{
		id: 0,
		author: 'Alyssa G.',
		avatar: '/reviewers/rev-v1.webp',
		title: 'Very Useful!',
		content: `Sobrang useful ng app na 'to! Mas napa bilis ma solve ang problema ko sa aircon namin. I'm so thankful relaxed na kami sa bahay.`,
		stars: 5,
	},
	{
		id: 1,
		author: 'Maxine L.',
		avatar: '/reviewers/rev-v2.webp',
		title: 'Super Easy!',
		content: `Wow! Grabe akala ko mahihirapan ako sa pag gamit ng app pero ang dali pala gamitin. Nag book ako ng carpenter kasi nasira bubong namin at ilang araw lang nagawa na agad! Thank you sir Tony!`,
		stars: 5,
	},
	{
		id: 2,
		author: 'Conielyn B.',
		avatar: '/reviewers/rev-v3.webp',
		title: 'Stars ka saken!',
		content: `My nail specialist Hannah is a pro! I got my nail extension today!! I will absolutely recommend her to my friends..`,
		stars: 5,
	},
	{
		id: 3,
		author: 'Nica V.',
		avatar: '/reviewers/rev-v4.webp',
		title: 'Professional!',
		content: `Lawrence fixed my broken pipe in the kitchen this morning. He is fast! Professional talaga at kumpleto sa tools!`,
		stars: 5,
	},
	{
		id: 4,
		author: 'Maddie B.',
		avatar: '/reviewers/rev-v5.webp',
		title: 'Ang Bilis!',
		content: `Tapos agad ni Ms Jiji yung taxation and financial records. Great job talaga!`,
		stars: 5,
	},
	{
		id: 5,
		author: 'Kris F.',
		avatar: '/reviewers/rev-v6.webp',
		title: 'Extra Money!',
		content: `This app is so easy to use for skilled workers like me. I earn extra for me and my family now! Thank you Outsourcee!!`,
		stars: 5,
	},
	{
		id: 6,
		author: 'Mariella E.',
		avatar: '/reviewers/rev-v7.webp',
		title: 'Ang Dali Kumita!',
		content: `Sa pag gawa lang in financial report ang alam ko pero grabe ang kita! Thank you so much Outsourcee!`,
		stars: 5,
	},
	{
		id: 7,
		author: 'Evangeline D.',
		avatar: 'https://github.com/amandavilela.png',
		title: 'Ang Husay!',
		content: `Mahusay talaga tong app na to. Mapagkakatiwalaan, in just 1 tap ang dami ng lumabas na skilled workers na aayos ng wiring sa sa kusina at sala ko. 5 stars!!`,
		stars: 5,
	},
]
